import React from 'react';
import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { systemApi } from '../api';
import { Activity, ShieldAlert, Cpu, HardDrive, Box, Layers, GitCommit, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';

const fetchBlueprint = async (repoId: string) => {
  return await systemApi.getBlueprint(repoId);
};

export default function RepositoryBlueprintPage() {
  const { repoId } = useParams();

  const { data: blueprint, isLoading, error } = useQuery({
    queryKey: ['blueprint', repoId],
    queryFn: () => fetchBlueprint(repoId as string),
    enabled: !!repoId,
  });

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-full min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (error || !blueprint) {
    return (
      <div className="flex justify-center items-center h-full min-h-[400px] text-destructive">
        <ShieldAlert className="w-8 h-8 mr-2" />
        Failed to load blueprint.
      </div>
    );
  }

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">Deployment Blueprint</h1>
          <p className="text-muted-foreground mt-2 flex items-center gap-2">
            <GitCommit className="w-4 h-4" />
            Generated by {blueprint.metadata?.generator} • Version {blueprint.metadata?.version}
          </p>
        </div>
      </div>

      {blueprint.warnings && blueprint.warnings.length > 0 && (
        <div className="bg-destructive/10 border border-destructive/20 rounded-xl p-4 flex flex-col gap-2">
          <div className="flex items-center text-destructive font-semibold">
            <AlertTriangle className="w-5 h-5 mr-2" />
            Warnings
          </div>
          <ul className="list-disc pl-5 text-sm text-destructive/80 space-y-1">
            {blueprint.warnings.map((w: string, i: number) => (
              <li key={i}>{w}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Readiness */}
        <div className="md:col-span-1 space-y-6">
          <div className="bg-card border border-border/50 rounded-xl p-6 shadow-sm">
            <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
              <Activity className="w-5 h-5 text-primary" />
              Readiness Score
            </h2>
            <div className="space-y-4">
              {Object.entries(blueprint.readiness || {}).map(([key, value]: [string, any]) => (
                <div key={key}>
                  <div className="flex justify-between items-center text-sm mb-1">
                    <span className="capitalize text-muted-foreground">{key}</span>
                    <span className="font-medium">{value.score}%</span>
                  </div>
                  <div className="w-full bg-secondary rounded-full h-2">
                    <div
                      className={`h-2 rounded-full ${value.score > 80 ? 'bg-green-500' : value.score > 50 ? 'bg-yellow-500' : 'bg-destructive'
                        }`}
                      style={{ width: `${value.score}%` }}
                    />
                  </div>
                  <p className="text-xs text-muted-foreground mt-1">{value.explanation}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-card border border-border/50 rounded-xl p-6 shadow-sm">
            <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
              <Layers className="w-5 h-5 text-primary" />
              Recommendations
            </h2>
            <div className="space-y-4">
              {blueprint.recommendations?.map((rec: any, idx: number) => (
                <div key={idx} className="bg-secondary/50 p-3 rounded-lg border border-border/50">
                  <h3 className="text-sm font-medium">{rec.value}</h3>
                  <p className="text-xs text-muted-foreground mt-1">{rec.reason}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Services & Strategy */}
        <div className="md:col-span-2 space-y-6">
          {blueprint.services?.map((service: any) => (
            <div key={service.name} className="bg-card border border-border/50 rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
              <div className="p-6 border-b border-border/50 bg-secondary/20 flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    <Box className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold capitalize">{service.name}</h2>
                    <p className="text-sm text-muted-foreground">Path: {service.path}</p>
                  </div>
                </div>
                <div className="flex gap-2">
                  <span className="px-3 py-1 bg-secondary rounded-full text-xs font-medium border border-border/50">
                    {service.language || 'Unknown'}
                  </span>
                  {service.framework?.name && (
                    <span className="px-3 py-1 bg-primary/10 text-primary rounded-full text-xs font-medium border border-primary/20">
                      {service.framework.name} ({(service.framework.confidence * 100).toFixed(0)}%)
                    </span>
                  )}
                </div>
              </div>

              <div className="p-6 grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div>
                  <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Infrastructure Detected</h3>
                  <ul className="space-y-2">
                    <li className="flex items-center text-sm gap-2">
                      {service.infrastructureStatus.dockerfileExists ? <CheckCircle className="w-4 h-4 text-green-500" /> : <XCircle className="w-4 h-4 text-muted-foreground" />}
                      Dockerfile
                    </li>
                    <li className="flex items-center text-sm gap-2">
                      {service.infrastructureStatus.composeExists ? <CheckCircle className="w-4 h-4 text-green-500" /> : <XCircle className="w-4 h-4 text-muted-foreground" />}
                      Docker Compose
                    </li>
                    <li className="flex items-center text-sm gap-2">
                      {service.infrastructureStatus.kubernetesExists ? <CheckCircle className="w-4 h-4 text-green-500" /> : <XCircle className="w-4 h-4 text-muted-foreground" />}
                      Kubernetes Manifests
                    </li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Strategy Details</h3>
                  <div className="space-y-2 text-sm">
                    <p className="flex justify-between"><span className="text-muted-foreground">Deployment:</span> <span className="font-medium capitalize">{service.deploymentStrategy.mode}</span></p>
                    <p className="flex justify-between"><span className="text-muted-foreground">Base Image:</span> <span className="font-medium">{service.buildStrategy.baseImage || 'N/A'}</span></p>
                    <p className="flex justify-between"><span className="text-muted-foreground">Ports:</span> <span className="font-medium">{service.ports?.join(', ') || 'None'}</span></p>
                  </div>
                </div>

                {blueprint.resources?.[service.name] && (
                  <div className="sm:col-span-2 pt-4 border-t border-border/50">
                    <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Estimated Resources</h3>
                    <div className="flex gap-4">
                      <div className="flex items-center gap-2 bg-secondary/50 px-3 py-2 rounded-lg border border-border/50">
                        <Cpu className="w-4 h-4 text-blue-500" />
                        <span className="text-sm font-medium">{blueprint.resources[service.name].cpu} vCPU</span>
                      </div>
                      <div className="flex items-center gap-2 bg-secondary/50 px-3 py-2 rounded-lg border border-border/50">
                        <HardDrive className="w-4 h-4 text-purple-500" />
                        <span className="text-sm font-medium">{blueprint.resources[service.name].ram} RAM</span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          ))}

          {blueprint.pipeline?.stages && (
            <div className="bg-card border border-border/50 rounded-xl p-6 shadow-sm">
              <h2 className="text-lg font-semibold flex items-center gap-2 mb-4">
                Pipeline Plan
              </h2>
              <div className="flex items-center overflow-x-auto pb-4 gap-2">
                {blueprint.pipeline.stages.map((stage: any, idx: number) => (
                  <React.Fragment key={idx}>
                    <div className="bg-secondary/50 px-4 py-2 rounded-lg border border-border/50 whitespace-nowrap text-sm font-medium">
                      {stage.name}
                    </div>
                    {idx < blueprint.pipeline.stages.length - 1 && (
                      <div className="text-muted-foreground">→</div>
                    )}
                  </React.Fragment>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
