import ConfigEntry from '../models/configEntry.model.js';
import Repository from '../models/repository.model.js';
import Environment from '../models/env.model.js';
import { resolveConfiguration as resolveNewConfig } from './configResolver.service.js';
import { decrypt } from '../utils/encryption.js';
import logger from '../utils/logger.js';

/**
 * Runtime Injection Service
 *
 * Produces the ResolvedConfiguration object consumed by all deployment
 * provider adapters (Docker, Compose, K8s, etc.). This is the single
 * contract between configuration storage and runtime injection.
*/

export async function resolveConfiguration(repositoryId, userId, environmentId) {
    // 1. Get repository metadata
    let repo = null;
    if (repositoryId) {
        repo = await Repository.findById(repositoryId).select('repoName provider').lean();
    }
    
    let env = null;
    if (environmentId) {
        env = await Environment.findById(environmentId).select('name slug').lean();
    }

    // 2. Resolve configuration using new resolver
    const resolvedArray = await resolveNewConfig(repositoryId, environmentId);

    // 3. Separate variables and secrets
    const variables = {};
    const secrets = {};
    let legacySecretsUsed = 0; // Keeping for compatibility

    for (const entry of resolvedArray) {
        const val = entry.encrypted ? decrypt(entry.value) : entry.value;
        if (entry.type === 'secret') {
            secrets[entry.name] = val;
        } else {
            variables[entry.name] = val;
        }
    }

    return {
        variables,
        secrets,
        metadata: {
            applicationId: repositoryId ? String(repositoryId) : null, // keep key for compatibility
            applicationSlug: repo?.repoName || null,
            environment: env?.slug || String(environmentId),
            provider: repo?.provider || 'docker',
            totalEntries: resolvedArray.length,
            variableCount: Object.keys(variables).length,
            secretCount: Object.keys(secrets).length,
            resolvedAt: new Date().toISOString(),
            legacySecretsUsed
        },
        warnings: [],
        missing: []
    };
}

// ── Provider Adapters ─────────────────────────────────────────────────────────

// Convert ResolvedConfiguration to Docker `-e` flags.

export function toDockerEnvFlags(resolved) {
    const flags = [];
    const merged = { ...resolved.variables, ...resolved.secrets };
    for (const [key, value] of Object.entries(merged)) {
        flags.push('-e', `${key}=${value}`);
    }
    return flags;
}

// Convert ResolvedConfiguration to a flat { KEY: VALUE } map.
// Used by docker.service.js createReplica().
export function toFlatMap(resolved) {
    return { ...resolved.variables, ...resolved.secrets };
}

// Convert ResolvedConfiguration to a .env file string.
// Suitable for Docker Compose env_file or manual download.
export function toEnvFile(resolved) {
    const lines = [];
    const merged = { ...resolved.variables, ...resolved.secrets };

    lines.push(`# Generated by DevOpsEase — ${resolved.metadata.environment}`);
    lines.push(`# Application: ${resolved.metadata.applicationSlug || 'unknown'}`);
    lines.push(`# Generated at: ${resolved.metadata.resolvedAt}`);
    lines.push('');

    // Variables first, then secrets
    if (Object.keys(resolved.variables).length > 0) {
        lines.push('# Variables');
        for (const [key, value] of Object.entries(resolved.variables)) {
            lines.push(`${key}=${value}`);
        }
        lines.push('');
    }

    if (Object.keys(resolved.secrets).length > 0) {
        lines.push('# Secrets');
        for (const [key, value] of Object.entries(resolved.secrets)) {
            lines.push(`${key}=${value}`);
        }
    }

    return lines.join('\n') + '\n';
}

// Convert ResolvedConfiguration to a Docker Compose `environment:` block object.
export function toComposeEnvironmentBlock(resolved) {
    return { ...resolved.variables, ...resolved.secrets };
}

// Convert resolved secrets to a Kubernetes Secret YAML string.

export function toK8sSecretYaml(name, namespace, resolved) {
    const data = {};
    for (const [key, value] of Object.entries(resolved.secrets)) {
        data[key] = Buffer.from(value).toString('base64');
    }

    const resource = {
        apiVersion: 'v1',
        kind: 'Secret',
        metadata: {
            name,
            namespace,
            labels: {
                'app.kubernetes.io/managed-by': 'devopsease',
            },
        },
        type: 'Opaque',
        data,
    };

    return toYamlString(resource);
}

// Convert resolved variables to a Kubernetes ConfigMap YAML string.

export function toK8sConfigMapYaml(name, namespace, resolved) {
    const resource = {
        apiVersion: 'v1',
        kind: 'ConfigMap',
        metadata: {
            name,
            namespace,
            labels: {
                'app.kubernetes.io/managed-by': 'devopsease',
            },
        },
        data: { ...resolved.variables },
    };

    return toYamlString(resource);
}

// Generate K8s envFrom block references for a pod spec.
export function toK8sEnvFrom(secretName, configMapName) {
    const envFrom = [];
    if (configMapName) {
        envFrom.push({ configMapRef: { name: configMapName } });
    }
    if (secretName) {
        envFrom.push({ secretRef: { name: secretName } });
    }
    return envFrom;
}

// ── YAML Serialization (lightweight, no dependency) ───────────────────────────

function toYamlString(obj, indent = 0) {
    const pad = ' '.repeat(indent);
    const lines = [];

    for (const [key, value] of Object.entries(obj)) {
        if (value === null || value === undefined) {
            lines.push(`${pad}${key}: null`);
        } else if (typeof value === 'string') {
            // Quote strings that contain special chars
            if (value.includes(':') || value.includes('#') || value.includes('\n') || value === '') {
                lines.push(`${pad}${key}: "${value.replace(/"/g, '\\"')}"`);
            } else {
                lines.push(`${pad}${key}: ${value}`);
            }
        } else if (typeof value === 'number' || typeof value === 'boolean') {
            lines.push(`${pad}${key}: ${value}`);
        } else if (Array.isArray(value)) {
            if (value.length === 0) {
                lines.push(`${pad}${key}: []`);
            } else {
                lines.push(`${pad}${key}:`);
                for (const item of value) {
                    if (typeof item === 'object' && item !== null) {
                        const subLines = toYamlString(item, indent + 4).split('\n');
                        lines.push(`${pad}  - ${subLines[0].trim()}`);
                        for (let i = 1; i < subLines.length; i++) {
                            if (subLines[i].trim()) {
                                lines.push(`${pad}    ${subLines[i].trim()}`);
                            }
                        }
                    } else {
                        lines.push(`${pad}  - ${item}`);
                    }
                }
            }
        } else if (typeof value === 'object') {
            lines.push(`${pad}${key}:`);
            lines.push(toYamlString(value, indent + 2));
        }
    }

    return lines.join('\n');
}

export default {
    resolveConfiguration,
    toDockerEnvFlags,
    toFlatMap,
    toEnvFile,
    toComposeEnvironmentBlock,
    toK8sSecretYaml,
    toK8sConfigMapYaml,
    toK8sEnvFrom,
};
